package com.yosri.defensy.backend.modules.ingestion.domain;

import lombok.*;
import org.springframework.data.annotation.Id;
import org.springframework.data.elasticsearch.annotations.Document;

import java.time.Instant;
import java.util.Map;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Document(indexName = "csv_ingestion") // ✅ Indexed in Elasticsearch
public class CsvIngestionRecord {

    @Id
    private String id; // ✅ Auto-generated by Elasticsearch

    private Map<String, String> data; // ✅ Flexible structure for CSV fields

    private Instant timestamp = Instant.now(); // ✅ Capture ingestion time
}
