package com.yosri.defensy.backend.modules.ingestion.domain;

import lombok.*;
import org.springframework.data.annotation.Id;
import org.springframework.data.elasticsearch.annotations.Document;

import java.time.Instant;
import java.util.Map;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Document(indexName = "csv_ingestion_search") // ✅ Stores CSV data in Elasticsearch for search & analytics
public class CsvIngestionSearchRecord {

    @Id
    private String id; // ✅ Auto-generated by Elasticsearch

    private Map<String, String> data; // ✅ Searchable structure for CSV fields
    private Instant timestamp; // ✅ Capture ingestion time dynamically
}
